### ISSUE TITLE
Pre-allocated constraint buffer is full. Increase njmax above 1000.

### ISSUE THREAD

**Issue by jasonseu** [facebookresearch/r3m#18]
Hi, thanks for your excellent work. When I run command to train R3M on kitchen_sdoor_open-v3 environment, it works fine at the beginning, but at a certain iteration it throws an error:

```
>>> python hydra_launcher.py hydra/launcher=local hydra/output=local env=kitchen_sdoor_open-v3 camera=left_cap2 pixel_based=true embedding=resnet50 num_demos=5 env_kwargs.load_path=r3m bc_kwargs.finetune=false bc_kwargs.save_logs=true proprio=9 seed=125 job_name=kitchen_sdoor_open-v3_left-cap2

...
Step 3955
Step 3962
Step 3969
Step 3976
Step 3983
Step 3990
Step 3997
Evaluating
Error executing job with overrides: ['env=kitchen_sdoor_open-v3', 'camera=left_cap2', 'pixel_based=true', 'embedding=resnet50', 'num_demos=5', 'env_kwargs.load_path=r3m', 'bc_kwargs.finetune=false', 'bc_kwargs.save_logs=true', 'proprio=9', 'seed=125', 'job_name=kitchen_sdoor_open-v3_left-cap2']
An error occurred during Hydra's exception formatting:
AssertionError()
Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 252, in run_and_report
    assert mdl is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hydra_launcher.py", line 42, in <module>
    configure_jobs()
  File "/home/tiger/.local/lib/python3.7/site-packages/hydra/main.py", line 52, in decorated_main
    config_name=config_name,
  File "/home/tiger/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 378, in _run_hydra
    lambda: hydra.run(
  File "/home/tiger/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 294, in run_and_report
    raise ex
  File "/home/tiger/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/tiger/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 381, in <lambda>
    overrides=args.overrides,
  File "/home/tiger/.local/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/tiger/.local/lib/python3.7/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/tiger/.local/lib/python3.7/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "hydra_launcher.py", line 38, in configure_jobs
    bc_train_loop(job_data)
  File "/opt/tiger/Robotics/r3m/evaluation/r3meval/core/train_loop.py", line 151, in bc_train_loop
    env_kwargs=env_kwargs)
  File "/opt/tiger/Robotics/r3m/evaluation/r3meval/utils/sampling.py", line 172, in sample_paths
    return do_rollout(**input_dict)
  File "/opt/tiger/Robotics/r3m/evaluation/r3meval/utils/sampling.py", line 95, in do_rollout
    o = env.reset()
  File "/opt/tiger/Robotics/r3m/evaluation/r3meval/utils/gym_env.py", line 91, in reset
    return self.env.reset()
  File "/home/tiger/.local/lib/python3.7/site-packages/gym/core.py", line 311, in reset
    return self.observation(self.env.reset(**kwargs))
  File "/home/tiger/.local/lib/python3.7/site-packages/gym/core.py", line 311, in reset
    return self.observation(self.env.reset(**kwargs))
  File "/home/tiger/.local/lib/python3.7/site-packages/gym/wrappers/time_limit.py", line 26, in reset
    return self.env.reset(**kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 18, in reset
    return self.env.reset(**kwargs)
  File "/opt/tiger/Robotics/lib/mj_envs/mj_envs/envs/relay_kitchen/kitchen_multitask_v2.py", line 335, in reset
    self.sim.step()
  File "mjsim.pyx", line 126, in mujoco_py.cymj.MjSim.step
  File "cymj.pyx", line 156, in mujoco_py.cymj.wrap_mujoco_warning.__exit__
  File "cymj.pyx", line 77, in mujoco_py.cymj.c_warning_callback
  File "/home/tiger/.local/lib/python3.7/site-packages/mujoco_py/builder.py", line 354, in user_warning_raise_exception
    raise MujocoException(warn + 'Increase njmax in mujoco XML')
mujoco_py.builder.MujocoException: Pre-allocated constraint buffer is full. Increase njmax above 1000. Time = 4.0040.Increase njmax in mujoco XML
```
I guess it may be caused by the buffer constrain of Mujoco. I have found parameter `njmax` related files under the fold `~/.mujoco/mujoco200/model`, but I have no idea which file should be modified. Do you have any advice?

**Comment by jasonseu** [comment]
I have found the Franka Kitchen related xml file under the fold `mj_envs/mj_envs/envs/relay_kitchen/assets`. Increasing njmax and nconmax in line 9 can solve the problem.
